# Generated by Django 5.1.6 on 2025-02-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Repetiteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.IntegerField(default=0, verbose_name='Nombre de pages'),
        ),
        migrations.AddField(
            model_name='document',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Popularité'),
        ),
    ]
